const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const founders = [
  // healthtech
  {
    name: 'Amirul Hakim bin Zulkifli',
    email: 'amirul@mediklink.my',
    company_name: 'MedikLink',
    stage: 'seed',
    industry: 'healthtech',
    pitch_summary: 'Connecting rural Malaysians to specialist doctors via AI-powered telemedicine with Bahasa Malaysia support.',
  },
  {
    name: 'Nurul Ain binti Rashid',
    email: 'nurul@sihatcare.my',
    company_name: 'SihatCare',
    stage: 'mvp',
    industry: 'healthtech',
    pitch_summary: 'Chronic disease management platform for Malaysian patients with diabetes and hypertension, integrated with MySejahtera.',
  },
  {
    name: 'Dr. Karthigeyan Subramaniam',
    email: 'karthi@docnow.com.my',
    company_name: 'DocNow',
    stage: 'series_a',
    industry: 'healthtech',
    pitch_summary: 'On-demand home visit and teleconsultation platform serving Klang Valley with 200+ panel doctors.',
  },
  {
    name: 'Siti Hajar binti Mohd Noor',
    email: 'sitihajar@bumilabs.my',
    company_name: 'BumiLabs Health',
    stage: 'idea',
    industry: 'healthtech',
    pitch_summary: 'Maternal health app tailored for Malay women, offering pregnancy tracking and nutrition guidance aligned with local dietary practices.',
  },
  {
    name: 'Lim Wei Xian',
    email: 'weixin@pharnex.my',
    company_name: 'PharNex',
    stage: 'mvp',
    industry: 'healthtech',
    pitch_summary: 'Digital pharmacy platform enabling prescription management and medication delivery across Peninsular Malaysia.',
  },

  // fintech
  {
    name: 'Ahmad Syafiq bin Hamdan',
    email: 'syafiq@bayarpay.my',
    company_name: 'BayarPay',
    stage: 'seed',
    industry: 'fintech',
    pitch_summary: 'BNPL solution for Malaysian SMEs purchasing B2B inventory, with Shariah-compliant financing options.',
  },
  {
    name: 'Priya Devindran',
    email: 'priya@koperatif.io',
    company_name: 'Koperatif Digital',
    stage: 'mvp',
    industry: 'fintech',
    pitch_summary: 'Modernising Malaysia\'s cooperative banking sector with a white-label digital banking core for koperasi.',
  },
  {
    name: 'Tan Kok Wai',
    email: 'kokwai@ringgitrobo.my',
    company_name: 'RinggitRobo',
    stage: 'seed',
    industry: 'fintech',
    pitch_summary: 'Robo-advisory platform targeting Malaysian millennials with automated, low-cost unit trust and ETF portfolios.',
  },
  {
    name: 'Nabilah binti Ismail',
    email: 'nabilah@zakatable.my',
    company_name: 'Zakatable',
    stage: 'mvp',
    industry: 'fintech',
    pitch_summary: 'Automated zakat calculation and payment platform integrated with Malaysian financial institutions and e-wallets.',
  },
  {
    name: 'Rajesh Pillai',
    email: 'rajesh@kredithub.my',
    company_name: 'KreditHub',
    stage: 'series_a',
    industry: 'fintech',
    pitch_summary: 'AI-driven credit scoring for the unbanked Malaysian workforce using payroll, utility, and telco data.',
  },

  // agritech
  {
    name: 'Mohd Farid bin Baharudin',
    email: 'farid@ladangpintar.my',
    company_name: 'Ladang Pintar',
    stage: 'seed',
    industry: 'agritech',
    pitch_summary: 'IoT-based precision farming platform for Malaysian paddy farmers, reducing water and fertiliser usage by 30%.',
  },
  {
    name: 'Chua Mei Ling',
    email: 'meiling@freshharvest.my',
    company_name: 'FreshHarvest',
    stage: 'mvp',
    industry: 'agritech',
    pitch_summary: 'Farm-to-table marketplace connecting Cameron Highlands vegetable farmers directly to Klang Valley retailers.',
  },
  {
    name: 'Azwan bin Che Mat',
    email: 'azwan@durianaI.my',
    company_name: 'DurianAI',
    stage: 'idea',
    industry: 'agritech',
    pitch_summary: 'Computer vision grading system for durian exporters to automate Musang King quality classification.',
  },
  {
    name: 'Selvakumar Rajan',
    email: 'selva@sawittech.my',
    company_name: 'SawitTech',
    stage: 'seed',
    industry: 'agritech',
    pitch_summary: 'Drone-based palm oil estate monitoring and yield prediction platform serving Sabah and Sarawak plantations.',
  },
  {
    name: 'Hartini binti Zainol',
    email: 'hartini@agrolink.my',
    company_name: 'AgroLink Malaysia',
    stage: 'mvp',
    industry: 'agritech',
    pitch_summary: 'Supply chain traceability platform for Malaysian organic produce, enabling export certification to the EU market.',
  },

  // edtech
  {
    name: 'Faizal bin Ahmad',
    email: 'faizal@kelasdigital.my',
    company_name: 'Kelas Digital',
    stage: 'series_a',
    industry: 'edtech',
    pitch_summary: 'Adaptive online learning platform for SPM students with AI-generated practice questions aligned to KSSM syllabus.',
  },
  {
    name: 'Wong Jing Yi',
    email: 'jingyi@tuisyenai.my',
    company_name: 'TuisyenAI',
    stage: 'seed',
    industry: 'edtech',
    pitch_summary: 'AI tutor providing personalised Mandarin, BM, and English tutoring for primary school students in Malaysia.',
  },
  {
    name: 'Munirah binti Kamarudin',
    email: 'munirah@skillrajin.my',
    company_name: 'SkillRajin',
    stage: 'mvp',
    industry: 'edtech',
    pitch_summary: 'Micro-credential platform for Malaysian blue-collar workers to upskill in technical trades with HRDC-claimable courses.',
  },
  {
    name: 'Dinesh Krishnasamy',
    email: 'dinesh@codewarrior.edu.my',
    company_name: 'Code Warrior Academy',
    stage: 'seed',
    industry: 'edtech',
    pitch_summary: 'Coding bootcamp for Malaysian youth aged 10-18 with gamified STEM curriculum in BM and English.',
  },
  {
    name: 'Roslina binti Hamid',
    email: 'roslina@madrasahdigital.my',
    company_name: 'Madrasah Digital',
    stage: 'idea',
    industry: 'edtech',
    pitch_summary: 'Islamic education platform offering interactive Quran memorisation and Fardhu Ain lessons for Malaysian families.',
  },

  // cleantech
  {
    name: 'Khairul Anwar bin Sulaiman',
    email: 'khairul@solarnation.my',
    company_name: 'SolarNation',
    stage: 'seed',
    industry: 'cleantech',
    pitch_summary: 'Solar-as-a-Service for Malaysian SMEs with zero upfront cost, managed via a real-time energy dashboard.',
  },
  {
    name: 'Lee Shu Ying',
    email: 'shuying@ecosort.my',
    company_name: 'EcoSort',
    stage: 'mvp',
    industry: 'cleantech',
    pitch_summary: 'AI-powered recycling kiosk network for Malaysian shopping malls, rewarding users with e-wallet credits.',
  },
  {
    name: 'Mohd Zaki bin Othman',
    email: 'zaki@hijauenergy.my',
    company_name: 'Hijau Energy',
    stage: 'series_a',
    industry: 'cleantech',
    pitch_summary: 'Green hydrogen production and distribution pilot for Malaysian industrial parks, targeting Net Zero 2050.',
  },
  {
    name: 'Anitha Krishnan',
    email: 'anitha@carbontrack.my',
    company_name: 'CarbonTrack MY',
    stage: 'mvp',
    industry: 'cleantech',
    pitch_summary: 'Carbon footprint monitoring and offset marketplace for Malaysian corporations meeting Bursa ESG reporting requirements.',
  },
  {
    name: 'Hazwan bin Mohd Yusof',
    email: 'hazwan@evcharge.my',
    company_name: 'EVCharge Malaysia',
    stage: 'seed',
    industry: 'cleantech',
    pitch_summary: 'EV charging network operator targeting residential condominiums and office buildings across Klang Valley.',
  },

  // logistics
  {
    name: 'Syahmi bin Roslan',
    email: 'syahmi@hantar.my',
    company_name: 'Hantar Express',
    stage: 'seed',
    industry: 'logistics',
    pitch_summary: 'Same-day last-mile delivery aggregator for Malaysian e-commerce sellers, comparing rates across 10+ couriers in real time.',
  },
  {
    name: 'Vivian Teh',
    email: 'vivian@gudangpintar.my',
    company_name: 'Gudang Pintar',
    stage: 'mvp',
    industry: 'logistics',
    pitch_summary: 'On-demand warehousing marketplace connecting Malaysian SME sellers with spare storage space owners.',
  },
  {
    name: 'Zulhilmi bin Razali',
    email: 'zulhilmi@freightmate.my',
    company_name: 'FreightMate',
    stage: 'series_a',
    industry: 'logistics',
    pitch_summary: 'Digital freight brokerage platform for Malaysia-Singapore cross-border trucking with real-time customs status tracking.',
  },
  {
    name: 'Kamala Devi Rajoo',
    email: 'kamala@coldchain.my',
    company_name: 'ColdChain Connect',
    stage: 'mvp',
    industry: 'logistics',
    pitch_summary: 'IoT temperature-monitoring solution for Malaysia\'s cold chain logistics, serving pharmaceutical and seafood exporters.',
  },
  {
    name: 'Hafizuddin bin Salleh',
    email: 'hafiz@poskilat.my',
    company_name: 'PosKilat',
    stage: 'idea',
    industry: 'logistics',
    pitch_summary: 'Hyperlocal 2-hour grocery delivery network for Tier-2 Malaysian cities using freelance motorcycle riders.',
  },

  // proptech
  {
    name: 'Daniel Ng Chun Kit',
    email: 'daniel@rumahpintar.my',
    company_name: 'RumahPintar',
    stage: 'seed',
    industry: 'proptech',
    pitch_summary: 'AI-powered property valuation and home-buying assistant for first-time Malaysian homeowners navigating PR1MA and PRIMA loans.',
  },
  {
    name: 'Norhaslinda binti Ghazali',
    email: 'linda@sewasmart.my',
    company_name: 'SewaSmart',
    stage: 'mvp',
    industry: 'proptech',
    pitch_summary: 'Rental management SaaS for Malaysian individual landlords to automate tenancy agreements, rent collection, and maintenance requests.',
  },
  {
    name: 'Samuel Voon',
    email: 'samuel@propex.my',
    company_name: 'PropEx',
    stage: 'series_a',
    industry: 'proptech',
    pitch_summary: 'Fractional real estate investment platform allowing Malaysians to co-invest in commercial properties from RM 1,000.',
  },
  {
    name: 'Rohaiza binti Abd Rahman',
    email: 'rohaiza@bandardigital.my',
    company_name: 'Bandar Digital',
    stage: 'idea',
    industry: 'proptech',
    pitch_summary: 'Smart city data platform aggregating Malaysian municipal data to help property developers identify high-growth township locations.',
  },
  {
    name: 'Goh Boon Huat',
    email: 'boonhuat@fitoutai.my',
    company_name: 'FitOut.ai',
    stage: 'mvp',
    industry: 'proptech',
    pitch_summary: 'AI interior design and renovation quoting tool for Malaysian homeowners, integrated with local contractor and material marketplaces.',
  },

  // govtech
  {
    name: 'Irfan bin Kamaluddin',
    email: 'irfan@rakyatconnect.my',
    company_name: 'RakyatConnect',
    stage: 'mvp',
    industry: 'govtech',
    pitch_summary: 'Civic engagement platform helping Malaysian local councils collect and triage resident feedback for municipal services.',
  },
  {
    name: 'Serena Loke',
    email: 'serena@permitsmart.my',
    company_name: 'PermitSmart',
    stage: 'seed',
    industry: 'govtech',
    pitch_summary: 'Digitising Malaysian business permit and licensing workflows for local authorities, cutting approval time from weeks to days.',
  },
  {
    name: 'Mohd Ridhwan bin Hashim',
    email: 'ridhwan@tendertrack.my',
    company_name: 'TenderTrack',
    stage: 'mvp',
    industry: 'govtech',
    pitch_summary: 'Government procurement transparency platform aggregating Malaysian Bumi tender opportunities with eligibility matching for SMEs.',
  },
  {
    name: 'Yasmin binti Roslan',
    email: 'yasmin@eaduan.my',
    company_name: 'eAduan',
    stage: 'idea',
    industry: 'govtech',
    pitch_summary: 'AI-powered complaint routing system for Malaysian government agencies to reduce inter-department handoff delays.',
  },
  {
    name: 'Nicholas Chai',
    email: 'nicholas@publicsafety.ai',
    company_name: 'PublicSafety.ai',
    stage: 'seed',
    industry: 'govtech',
    pitch_summary: 'Predictive analytics dashboard for Malaysian police to optimise patrol resource allocation using crime trend data.',
  },

  // hrtech
  {
    name: 'Azizah binti Talib',
    email: 'azizah@kerjaya.my',
    company_name: 'Kerjaya Platform',
    stage: 'series_a',
    industry: 'hrtech',
    pitch_summary: 'Talent marketplace connecting Malaysian gig workers to corporate projects with built-in EPF and SOCSO contribution management.',
  },
  {
    name: 'Kevin Yeap',
    email: 'kevin@hrflow.my',
    company_name: 'HRFlow Malaysia',
    stage: 'seed',
    industry: 'hrtech',
    pitch_summary: 'All-in-one HR and payroll SaaS for Malaysian SMEs under 200 headcount, compliant with EA 1955 and PCB deductions.',
  },
  {
    name: 'Fazilah binti Mohamad',
    email: 'fazilah@talentpadu.my',
    company_name: 'TalentPadu',
    stage: 'mvp',
    industry: 'hrtech',
    pitch_summary: 'Employer branding and structured interview platform helping Malaysian GLCs attract and retain Gen-Z talent.',
  },
  {
    name: 'Suresh Nair',
    email: 'suresh@workwellmy.com',
    company_name: 'WorkWell Malaysia',
    stage: 'mvp',
    industry: 'hrtech',
    pitch_summary: 'Employee mental wellness platform for Malaysian companies, offering confidential counselling, mood tracking, and burnout early-warning.',
  },
  {
    name: 'Hasmah binti Yusuf',
    email: 'hasmah@skillsverify.my',
    company_name: 'SkillsVerify',
    stage: 'idea',
    industry: 'hrtech',
    pitch_summary: 'Blockchain-based professional credentials verification for Malaysian employers to instantly authenticate candidate qualifications.',
  },

  // cybersecurity
  {
    name: 'Farhan bin Alias',
    email: 'farhan@selamatnet.my',
    company_name: 'SelamatNet',
    stage: 'seed',
    industry: 'cybersecurity',
    pitch_summary: 'Managed security operations centre (SOC) for Malaysian SMEs, providing 24/7 threat detection at an SME-accessible price point.',
  },
  {
    name: 'Jason Hoo Wei Lun',
    email: 'jason@phishguard.my',
    company_name: 'PhishGuard',
    stage: 'mvp',
    industry: 'cybersecurity',
    pitch_summary: 'AI-powered phishing simulation and security awareness training platform tailored for Malaysian banking and finance employees.',
  },
  {
    name: 'Norzaini binti Wahab',
    email: 'norzaini@dataprotect.my',
    company_name: 'DataProtect MY',
    stage: 'mvp',
    industry: 'cybersecurity',
    pitch_summary: 'PDPA compliance SaaS helping Malaysian organisations audit, document, and manage personal data processing activities.',
  },
  {
    name: 'Balakrishnan Perumal',
    email: 'bala@threatintel.my',
    company_name: 'ThreatIntel Malaysia',
    stage: 'seed',
    industry: 'cybersecurity',
    pitch_summary: 'Cyber threat intelligence feed aggregating ASEAN-specific indicators of compromise for Malaysian CERTs and financial institutions.',
  },
  {
    name: 'Hafeeza binti Mokhtar',
    email: 'hafeeza@secureid.my',
    company_name: 'SecureID',
    stage: 'series_a',
    industry: 'cybersecurity',
    pitch_summary: 'Biometric digital identity verification platform for Malaysian fintech and telco onboarding, integrated with MyKad NFC chip.',
  },
];

const mentors = [
  {
    name: 'Dato\' Sri Mohd Fadzillah bin Ibrahim',
    email: 'fadzillah@mentormy.com',
    expertise: ['venture capital', 'startup strategy', 'fundraising'],
    industry: ['fintech', 'healthtech'],
    capacity: 4,
    success_rate: 0.88,
    past_cohorts: 6,
    bio: 'Former MD at Cradle Fund and founding partner of a Kuala Lumpur VC firm with 40+ Malaysian portfolio companies. Passionate about growing the next generation of Malaysian tech founders.',
    availability: true,
  },
  {
    name: 'Puan Rosnah binti Abdul Wahid',
    email: 'rosnah@digitalmentors.my',
    expertise: ['digital transformation', 'government relations', 'product management'],
    industry: ['govtech', 'hrtech'],
    capacity: 3,
    success_rate: 0.82,
    past_cohorts: 4,
    bio: 'Ex-MDEC director who led Malaysia\'s Digital Economy Blueprint implementation. Now advises startups on navigating public sector procurement and policy engagement.',
    availability: true,
  },
  {
    name: 'Dr. Vijayakumar Krishnasamy',
    email: 'vijay@healthventures.my',
    expertise: ['clinical operations', 'regulatory affairs', 'medical devices'],
    industry: ['healthtech'],
    capacity: 3,
    success_rate: 0.79,
    past_cohorts: 5,
    bio: 'Physician-turned-entrepreneur who founded and exited two Malaysian health-tech companies. Deep expertise in MDA device licensing and MOH approval processes.',
    availability: true,
  },
  {
    name: 'Chong Li Shan',
    email: 'lishan@agrimentor.my',
    expertise: ['supply chain', 'rural market entry', 'impact investing'],
    industry: ['agritech', 'cleantech'],
    capacity: 4,
    success_rate: 0.75,
    past_cohorts: 3,
    bio: 'Built and scaled a Malaysian agri-logistics company to a RM 50M exit. Active contributor to Agrobank\'s startup advisory panel and Khazanah sustainability initiatives.',
    availability: true,
  },
  {
    name: 'Sharifah Nadia binti Syed Hussain',
    email: 'nadia@womenfounder.my',
    expertise: ['brand strategy', 'community building', 'edtech product design'],
    industry: ['edtech', 'hrtech'],
    capacity: 5,
    success_rate: 0.84,
    past_cohorts: 7,
    bio: 'Co-founder of Malaysia\'s leading women-in-tech network and two-time edtech founder. Championing inclusive tech and rural digital literacy across the peninsula.',
    availability: true,
  },
  {
    name: 'Marcus Tan Eng Huat',
    email: 'marcus@propmentors.my',
    expertise: ['real estate finance', 'product-market fit', 'growth hacking'],
    industry: ['proptech', 'fintech'],
    capacity: 3,
    success_rate: 0.77,
    past_cohorts: 4,
    bio: 'Serial proptech entrepreneur with two exits in Malaysia and Singapore. Former head of product at iProperty Group; now angel investor in SEA proptech and fintech.',
    availability: true,
  },
  {
    name: 'Ts. Mohd Hazri bin Hashim',
    email: 'hazri@cybermentors.my',
    expertise: ['cybersecurity architecture', 'PDPA compliance', 'penetration testing'],
    industry: ['cybersecurity', 'govtech'],
    capacity: 3,
    success_rate: 0.91,
    past_cohorts: 5,
    bio: 'Registered Technologist (Ts.) with 20 years in Malaysian cybersecurity. Former NACSA technical lead; now CTO of a listed Malaysian security firm and startup mentor.',
    availability: true,
  },
  {
    name: 'Lim Bee Geok',
    email: 'beegeok@supplychain.my',
    expertise: ['logistics operations', 'last-mile delivery', 'e-commerce'],
    industry: ['logistics', 'proptech'],
    capacity: 4,
    success_rate: 0.80,
    past_cohorts: 6,
    bio: 'Built Pos Malaysia\'s e-commerce logistics arm from zero to 1M parcels/month. Now advising Malaysian logistics and supply chain startups on unit economics and ops scaling.',
    availability: true,
  },
  {
    name: 'Tengku Amiruddin bin Tengku Zainal',
    email: 'amiruddin@islamicfintech.my',
    expertise: ['Islamic finance', 'Shariah compliance', 'capital markets'],
    industry: ['fintech', 'govtech'],
    capacity: 3,
    success_rate: 0.85,
    past_cohorts: 4,
    bio: 'Senior partner at a Malaysian Islamic finance law firm and former SC Malaysia FinTech facilitator. Expert in SC Digital Asset licensing and waqf fintech innovation.',
    availability: true,
  },
  {
    name: 'Kavitha Subramaniam',
    email: 'kavitha@hrmentors.my',
    expertise: ['talent management', 'organisational design', 'employer branding'],
    industry: ['hrtech', 'edtech'],
    capacity: 4,
    success_rate: 0.78,
    past_cohorts: 3,
    bio: 'Former CHRO at a FTSE-listed Malaysian conglomerate with 8,000 employees. Passionate about helping HR startups understand the enterprise buyer journey.',
    availability: true,
  },
  {
    name: 'Dr. Aminah binti Md Zain',
    email: 'aminah@cleanenergy.my',
    expertise: ['renewable energy policy', 'carbon markets', 'project finance'],
    industry: ['cleantech', 'agritech'],
    capacity: 3,
    success_rate: 0.83,
    past_cohorts: 5,
    bio: 'PhD in Environmental Engineering from UTM. Led Malaysia\'s first Green Technology Financing Scheme at KeTTHA; now advising cleantech and greentech startups on grants and policy.',
    availability: true,
  },
  {
    name: 'Raymond Yap Chee Leong',
    email: 'raymond@scaleup.my',
    expertise: ['SaaS growth', 'enterprise sales', 'SEA market expansion'],
    industry: ['hrtech', 'fintech', 'logistics'],
    capacity: 5,
    success_rate: 0.86,
    past_cohorts: 8,
    bio: 'Three-time SaaS founder; last company scaled to USD 10M ARR across Malaysia, Thailand, and Indonesia. Now a full-time mentor and angel investor at 500 Global.',
    availability: true,
  },
  {
    name: 'Pn. Faridah binti Arshad',
    email: 'faridah@govadviser.my',
    expertise: ['public policy', 'community engagement', 'social enterprise'],
    industry: ['govtech', 'edtech'],
    capacity: 3,
    success_rate: 0.74,
    past_cohorts: 4,
    bio: 'Former state economic planning unit director with expertise in Malaysia\'s Economic Planning Unit (EPU) grant ecosystem. Helps social startups navigate MyStartup and MTDC programmes.',
    availability: true,
  },
  {
    name: 'Ken Foong Wei Sheng',
    email: 'ken@deeptech.my',
    expertise: ['AI/ML engineering', 'data infrastructure', 'product development'],
    industry: ['healthtech', 'cybersecurity'],
    capacity: 4,
    success_rate: 0.89,
    past_cohorts: 6,
    bio: 'Ex-Google Brain researcher turned Malaysian deep-tech founder. Exited his AI diagnostics startup to a Singapore MedTech firm; now mentoring AI-first Malaysian startups.',
    availability: true,
  },
  {
    name: 'Norashikin binti Daud',
    email: 'norashikin@ruraltech.my',
    expertise: ['rural market development', 'microfinance', 'community co-operatives'],
    industry: ['agritech', 'fintech'],
    capacity: 4,
    success_rate: 0.76,
    past_cohorts: 3,
    bio: 'Led Amanah Ikhtiar Malaysia\'s digital microfinance pilot reaching 50,000 rural women borrowers. Specialist in last-mile adoption strategies for underserved Malaysian communities.',
    availability: true,
  },
  {
    name: 'Darren Lau Kah Wai',
    email: 'darren@propinvest.my',
    expertise: ['real estate investment', 'crowdfunding regulation', 'investor relations'],
    industry: ['proptech', 'fintech'],
    capacity: 3,
    success_rate: 0.81,
    past_cohorts: 5,
    bio: 'Structured Malaysia\'s first SC-licensed real estate equity crowdfunding platform. Former investment banker at CIMB; now helping proptech and fintech startups with regulatory strategy.',
    availability: true,
  },
  {
    name: 'Dr. Syed Naquib al-Faruqi',
    email: 'naquib@islamictech.my',
    expertise: ['digital ethics', 'Islamic innovation', 'halal certification'],
    industry: ['healthtech', 'edtech', 'fintech'],
    capacity: 3,
    success_rate: 0.72,
    past_cohorts: 2,
    bio: 'Academic researcher at IIUM turned startup advisor. Advises Malaysian startups on Islamic-compliant product development and halal digital economy opportunities.',
    availability: true,
  },
  {
    name: 'Melissa Wong Swee Lin',
    email: 'melissa@brandgrowth.my',
    expertise: ['consumer marketing', 'brand building', 'influencer strategy'],
    industry: ['edtech', 'hrtech', 'proptech'],
    capacity: 5,
    success_rate: 0.87,
    past_cohorts: 7,
    bio: 'CMO who scaled two Malaysian B2C startups to regional reach. Expert in Malaysian consumer behaviour across Malay, Chinese, and Indian market segments.',
    availability: true,
  },
  {
    name: 'Ahmad Fauzi bin Mat Isa',
    email: 'fauzi@legaltech.my',
    expertise: ['startup law', 'equity structuring', 'IP protection'],
    industry: ['cybersecurity', 'govtech', 'fintech'],
    capacity: 4,
    success_rate: 0.80,
    past_cohorts: 5,
    bio: 'Partner at a Malaysian tech law firm specialising in startup incorporations, term sheet negotiations, and IP registration. Advised 100+ Malaysian startups on legal foundations.',
    availability: true,
  },
  {
    name: 'Ts. Yusnita binti Mohd Yusof',
    email: 'yusnita@iotlab.my',
    expertise: ['IoT engineering', 'hardware prototyping', 'manufacturing'],
    industry: ['agritech', 'cleantech', 'logistics'],
    capacity: 3,
    success_rate: 0.83,
    past_cohorts: 4,
    bio: 'Registered Technologist with expertise in IoT hardware development and Malaysian SIRIM certification. Former R&D lead at a Penang electronics MNC; now supporting hardware startups.',
    availability: true,
  },
];

async function main() {
  let founderCount = 0;
  let mentorCount = 0;

  for (const founder of founders) {
    await prisma.founder.upsert({
      where: { email: founder.email },
      update: founder,
      create: founder,
    });
    founderCount++;
  }

  for (const mentor of mentors) {
    await prisma.mentor.upsert({
      where: { email: mentor.email },
      update: mentor,
      create: mentor,
    });
    mentorCount++;
  }

  console.log(`Seeded ${founderCount} founders and ${mentorCount} mentors.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
